######################################################################
# Automatically generated by qmake (3.1) Thu Jun 13 22:54:34 2024
######################################################################

TEMPLATE = app
TARGET = wallet
INCLUDEPATH += .
QT       += core gui widgets

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += \
           src/account_editor.h \
           src/account_widget.h \
           src/add_account_window.h \
           src/add_category_window.h \
           src/add_inc_dec.h \
           src/add_transfer_window.h \
           src/binary_loader.h \
           src/category_editor.h \
           src/cell_w.h \
           src/domain.h \
           src/first_w.h \
           src/first_window.h \
           src/mainwindow.h \
           src/model.h \
           src/model_representation.h \
           src/serialization.h \
           src/transaction_editor.h \
           src/transactions_manager.h
SOURCES += \
           src/account_editor.cpp \
           src/account_widget.cpp \
           src/add_account_window.cpp \
           src/add_category_window.cpp \
           src/add_inc_dec.cpp \
           src/add_transfer_window.cpp \
           src/binary_loader.cpp \
           src/category_editor.cpp \
           src/cell_w.cpp \
           src/domain.cpp \
           src/first_w.cpp \
           src/first_window.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/model.cpp \
           src/model_representation.cpp \
           src/serialization.cpp \
           src/transaction_editor.cpp \
           src/transactions_manager.cpp
